# Form implementation generated from reading ui file 'tab7.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_tab7_frame(object):
    def setupUi(self, tab7_frame):
        tab7_frame.setObjectName("tab7_frame")
        tab7_frame.resize(911, 584)
        self.centralwidget = QtWidgets.QWidget(parent=tab7_frame)
        self.centralwidget.setObjectName("centralwidget")
        self.graphicsView = QtWidgets.QGraphicsView(parent=self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(0, 10, 571, 351))
        self.graphicsView.setObjectName("graphicsView")
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 370, 891, 181))
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.textBrowser = QtWidgets.QTextBrowser(parent=self.frame)
        self.textBrowser.setGeometry(QtCore.QRect(10, 0, 771, 192))
        self.textBrowser.setObjectName("textBrowser")
        self.pushButton = QtWidgets.QPushButton(parent=self.frame)
        self.pushButton.setGeometry(QtCore.QRect(790, 10, 75, 24))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.frame)
        self.pushButton_2.setGeometry(QtCore.QRect(790, 50, 75, 24))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(parent=self.frame)
        self.pushButton_3.setGeometry(QtCore.QRect(790, 90, 75, 24))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(parent=self.frame)
        self.pushButton_4.setGeometry(QtCore.QRect(790, 140, 75, 24))
        self.pushButton_4.setObjectName("pushButton_4")
        self.frame_2 = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(570, 10, 331, 351))
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.graphicsView_2 = QtWidgets.QGraphicsView(parent=self.frame_2)
        self.graphicsView_2.setGeometry(QtCore.QRect(10, 40, 311, 311))
        self.graphicsView_2.setObjectName("graphicsView_2")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(parent=self.frame_2)
        self.plainTextEdit.setGeometry(QtCore.QRect(10, 0, 311, 31))
        self.plainTextEdit.setObjectName("plainTextEdit")
        tab7_frame.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=tab7_frame)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 911, 22))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(parent=self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(parent=self.menubar)
        self.menu_2.setObjectName("menu_2")
        tab7_frame.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=tab7_frame)
        self.statusbar.setObjectName("statusbar")
        tab7_frame.setStatusBar(self.statusbar)
        self.action123132 = QtGui.QAction(parent=tab7_frame)
        self.action123132.setObjectName("action123132")
        self.menu.addAction(self.action123132)
        self.menu.addSeparator()
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())

        self.retranslateUi(tab7_frame)
        QtCore.QMetaObject.connectSlotsByName(tab7_frame)

    def retranslateUi(self, tab7_frame):
        _translate = QtCore.QCoreApplication.translate
        tab7_frame.setWindowTitle(_translate("tab7_frame", "MainWindow"))
        self.pushButton.setText(_translate("tab7_frame", "打开文件夹1"))
        self.pushButton_2.setText(_translate("tab7_frame", "打开文件夹2"))
        self.pushButton_3.setText(_translate("tab7_frame", "打开文件夹3"))
        self.pushButton_4.setText(_translate("tab7_frame", "打开报告"))
        self.plainTextEdit.setPlainText(_translate("tab7_frame", "Path/to/file"))
        self.menu.setTitle(_translate("tab7_frame", "设置菜单"))
        self.menu_2.setTitle(_translate("tab7_frame", "设置菜单2"))
        self.action123132.setText(_translate("tab7_frame", "123132"))
