# Form implementation generated from reading ui file 'tab7.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_tab7_frame(object):
    def setupUi(self, tab7_frame):
        tab7_frame.setObjectName("tab7_frame")
        tab7_frame.resize(911, 584)
        self.centralwidget = QtWidgets.QWidget(parent=tab7_frame)
        self.centralwidget.setObjectName("centralwidget")
        self.image_view = QtWidgets.QGraphicsView(parent=self.centralwidget)
        self.image_view.setGeometry(QtCore.QRect(0, 10, 571, 351))
        self.image_view.setObjectName("image_view")
        self.status_frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.status_frame.setGeometry(QtCore.QRect(0, 370, 891, 181))
        self.status_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.status_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.status_frame.setObjectName("status_frame")
        self.statusBrowser = QtWidgets.QTextBrowser(parent=self.status_frame)
        self.statusBrowser.setGeometry(QtCore.QRect(10, 0, 711, 171))
        self.statusBrowser.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOn)
        self.statusBrowser.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOn)
        self.statusBrowser.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.SizeAdjustPolicy.AdjustToContents)
        self.statusBrowser.setObjectName("statusBrowser")
        self.openFL_btn = QtWidgets.QPushButton(parent=self.status_frame)
        self.openFL_btn.setGeometry(QtCore.QRect(750, 10, 121, 24))
        self.openFL_btn.setObjectName("openFL_btn")
        self.openYL_btn = QtWidgets.QPushButton(parent=self.status_frame)
        self.openYL_btn.setGeometry(QtCore.QRect(750, 50, 121, 24))
        self.openYL_btn.setObjectName("openYL_btn")
        self.openSL_btn = QtWidgets.QPushButton(parent=self.status_frame)
        self.openSL_btn.setGeometry(QtCore.QRect(750, 90, 121, 24))
        self.openSL_btn.setObjectName("openSL_btn")
        self.openReport_btn = QtWidgets.QPushButton(parent=self.status_frame)
        self.openReport_btn.setGeometry(QtCore.QRect(770, 140, 75, 24))
        self.openReport_btn.setObjectName("openReport_btn")
        self.graphic_frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.graphic_frame.setGeometry(QtCore.QRect(570, 10, 331, 351))
        self.graphic_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.graphic_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.graphic_frame.setObjectName("graphic_frame")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(parent=self.graphic_frame)
        self.plainTextEdit.setGeometry(QtCore.QRect(10, 0, 311, 31))
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=self.graphic_frame)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 40, 311, 311))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.charts_layout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.charts_layout.setContentsMargins(0, 0, 0, 0)
        self.charts_layout.setObjectName("charts_layout")
        tab7_frame.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=tab7_frame)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 911, 22))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(parent=self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(parent=self.menubar)
        self.menu_2.setObjectName("menu_2")
        tab7_frame.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=tab7_frame)
        self.statusbar.setObjectName("statusbar")
        tab7_frame.setStatusBar(self.statusbar)
        self.action123132 = QtGui.QAction(parent=tab7_frame)
        self.action123132.setObjectName("action123132")
        self.menu.addAction(self.action123132)
        self.menu.addSeparator()
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())

        self.retranslateUi(tab7_frame)
        QtCore.QMetaObject.connectSlotsByName(tab7_frame)

    def retranslateUi(self, tab7_frame):
        _translate = QtCore.QCoreApplication.translate
        tab7_frame.setWindowTitle(_translate("tab7_frame", "MainWindow"))
        self.statusBrowser.setHtml(_translate("tab7_frame", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Microsoft YaHei UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.openFL_btn.setText(_translate("tab7_frame", "打开蜚蠊存档文件夹"))
        self.openYL_btn.setText(_translate("tab7_frame", "打开蝇类存档文件夹"))
        self.openSL_btn.setText(_translate("tab7_frame", "打开鼠类存档文件夹"))
        self.openReport_btn.setText(_translate("tab7_frame", "打开报告"))
        self.plainTextEdit.setPlainText(_translate("tab7_frame", "Path/to/file"))
        self.menu.setTitle(_translate("tab7_frame", "设置菜单"))
        self.menu_2.setTitle(_translate("tab7_frame", "设置菜单2"))
        self.action123132.setText(_translate("tab7_frame", "123132"))
